### ISSUE TITLE
camptocamp-systemd is deprecated

### ISSUE THREAD

**Issue by XMol** [unibonn/puppet-cobald#14]
Hi,

the [camptocamp-systemd](https://forge.puppet.com/modules/camptocamp/systemd) module is deprecated now and this project of yours still states a dependency for it. Please consider switching to a different module, e.g. [voxpupuli-systemd](https://forge.puppet.com/modules/puppet/systemd).

Thanks,  
Xavier.

**Comment by wiene** [comment]
@XMol thanks for bringing this issue to our attention. We will look into migrating our infrastructure and this module to [`voxpupuli/systemd`](https://github.com/voxpupuli/puppet-systemd).

**Comment by XMol** [comment]
Hi @wiene, @olifre, any update on this?

**Comment by olifre** [comment]
Hi @XMol , we are sadly still on it — many profile classes and other modules in our stack are not yet up-to-date, using deprecated / removed parts of `camptocamp/puppet-systemd`. We have slowly migrated up to `camptocamp/puppet-systemd-2.12.0` which is not very far from the migration to Voxpopuli, so we should not be very far from achieving the switch. 
Sorry for the long delays.

**Comment by olifre** [comment]
Hi @XMol , that was faster than expected after a short marathon — PR open, soon to be merged. Sorry again for the long wait!
