### ISSUE TITLE
Deprecated dependency camptocamp/systemd

### ISSUE THREAD

**Issue by maxfischer2781** [unibonn/puppet-cobald#15]
The dependency [camptocamp/systemd](https://forge.puppet.com/modules/camptocamp/systemd) is deprecated.

> This module has been deprecated by its author since Aug 16th 2021.
> **The reason given was:** *No longer maintained*
> The author has suggested [puppet-systemd](https://forge.puppet.com/modules/puppet/systemd) as its replacement.

I haven't checked whether the puppet-systemd is just a drop-in replacement or requires code changes.

**Comment by XMol** [comment]
Yeah, I won by 1 minute. 😎
